name: calling-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  run-org-wide-pre-commit-hook:
    uses: asenindbt/reusable-workflow-poc/.github/workflows/run-org-wide-hook.yml@main

  repo-specific-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Run repo specific tasks here
        run: |
          echo "Add repo specific tasks here"

#  copy-pre-commit:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout current repo
#        uses: actions/checkout@v4
#
#      - name: Checkout source repo
#        uses: actions/checkout@v4
#        with:
#          repository: 'asenindbt/reusable-workflow-poc'
#          path: 'reusable-workflow-poc'
#          ref: 'main'

#      - name: Check file directory
#        run: |
#          ls -la reusable-workflow-poc
#
#      - name: Copy pre-commit file to target repo
#        run: |
#          cp reusable-workflow-poc/orghooks.yaml .
#
#      - name: Check root directory
#        run: |
#          ls -la
#
#      - name: Set up Python 3.10
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.10"
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pre-commit
#
#      - name: Run org-wide pre-commit hook
#        run: |
#          pre-commit run --config "./orghooks.yaml" --all-files
