# This is a basic workflow to help you get started with Actions

name: calling-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: 'asenindbt/reusable-workflow-poc'
          path: 'reusable-workflow-poc'
          ref: 'main'

      - name: Check file directory
        run: |
          ls -la reusable-workflow-poc

      - name: Copy pre-commit file to target repo
        run: |
          cp reusable-workflow-poc/orghooks.yaml .

      - name: Check root directory
        run: |
          ls -la

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

